### ISSUE TITLE
iPad Editor: Create new note action doesn't save the currently opened note

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-ios#935] opened 2020-10-20 11:30 UTC
In certain conditions last changes made to the currently opened note are not persisted when "Create New Note" button is pressed.

### Expected
All changes should be persisted.

### Observed
Changes are lost.

### Reproduced
On iPad:
1. Open a note
2. Change something
3. Without waiting long (before the timer to save note is fired) tap on "Create New Note" button
4. Go back to the list and open the note from step 1
5. Changes are lost

**Comment by jleandroperez** [comment] 2020-11-06 19:21
Closed as duplicate of #811

Thank you Evgeny!

**Closed as completed by jleandroperez** 2020-11-06 19:21 UTC
Labels: bug
