### ISSUE TITLE
[Notes List] 'No Notes' icon is shown after notes were created

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#944] opened 2020-10-23 21:17 UTC
### Expected
'No Notes' string and Simplenote logo, both at the center of notes list, should be shown only in case where there are no notes

### Observed
After certain scenario of notes creation, both created notes, and 'No Notes' string is shown.

### Reproduced
> 1. Make sure there are no notes, and you can see 'No Notes' string at the main screen
> 2. Tap 'add note' icon, enter any text
> 3. Tap 'hide keyboard' icon and tap 'add note' icon that has appeared instead of 'hide keyboard'
> 4. Enter any text for the new (2nd) note
> 5. Go back to the list by taping '< Notes' 
> 6. You will see the new notes and 'No Notes' string at the same time (see picture below)

![photo_2020-10-24_00-11-58](https://user-images.githubusercontent.com/73365754/97054687-e74bab00-158d-11eb-9463-7badc290dc42.jpg)

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.0.1|4.26

**Comment by jleandroperez** [comment] 2020-10-23 21:47
Thank you for the bug report!

**Comment by charliescheer** [comment] 2021-01-13 21:38
Was not able to reproduce with given steps with iOS 14.3, SN 4.29
closing for now

**Closed as completed by charliescheer** 2021-01-13 21:38 UTC
Labels: bug

**Comment by pachlava** [comment] 2021-01-14 10:07
Confirm, it's not reproducible in SN 4.29 for me too.
The 'background logo' and its behaviour had changed since 4.26.
