### ISSUE TITLE
a little bug about long press to select text

### ISSUE THREAD

**Issue by isBral** [Automattic/simplenote-ios#144] opened 2017-05-19 03:22 UTC
I have a long note more than one screen, If i want long press to select some text at bottom of the screen, The keyboard will automatically pop up, When I release my finger, Select text mark will jump to other places. 
so i hope simplenote like ios note, when i long press to select text, the keyboard will not auto popup, if i one click text, the keyboard popup.

**Comment by bummytime** [comment] 2019-05-14 03:25
Thanks for the issue report @isBral. Verified on iOS 12.2, Simplenote 4.7.0

**Comment by ChrissiePollock** [comment] 2019-09-27 15:33
Perhaps similar - #2382276-zen. ...Impossible to use the text handles now. I can’t really select words using them. Simplenote version 4.10.1.

**Comment by ChrissiePollock** [comment] 2019-09-27 15:37
Another report with a screencast - #2378858-zen.

**Comment by jleandroperez** [comment] 2020-02-20 17:40
I've added this to our feature requests. Thanks for the suggestion everyone!

**Comment by jleandroperez** [comment] 2020-02-20 17:41
Oops, wrong window. Reopening, apologies about the noise!

**Comment by rossanafmenezes** [comment] 2020-11-25 12:47
This one seems to be a similar issue 3490581-zen

user is having problems selecting text and moving the cursor. There's a video on the ticket showing the issue. 

Iphone XS, iOS 14.2, Simplenote 4.2.7

**Comment by rossanafmenezes** [comment] 2020-12-02 17:06
Another report here 3529749-zen 

app version 4.27
iPad mini (5th generation) 
iOS 14

There's a video in the ticket of how it is behaving when the user tries to select text from a note

**Comment by charliescheer** [comment] 2021-01-11 03:14
I have looked all of these comments over, and they are all variations on a theme, but not exactly the same issue.  For the issue described in the original report, that when **long pressing near the bottom of the screen it does not select the text but instead moves the cursor to another location**, at this time long pressing on Simplenote puts the cursor into scan mode where you can easily drag the cursors around the available text.  As near as I can tell that is expected behavior.

The issue brought up in 3529749-zen, 2378858-zen, 2382276-zen are all issues with **tapping on text to select** it.  Currently tapping on text has the following affects:
First tap: Moves cursor to location, checks spelling of word that was tapped on (if the word is not recognized by the dictionary)
Quick double tap: Highlights word and brings up text options (copy/paste/cut/etc)
(note if tapped on an empty space the last word is highlighted

Slow double tap:  If you tap on a word, wait a second and then tap on the word again the word is highlighted but the text options do not appear
Slow triple tap:  If you use the slow double tap option and then tap a third time the text options appear

This all seems to me to be expected behavior, but maybe not the most straight forward.  

Looking at the videos shared in the tickets above, it seems that the behavior has improved since many of them were made, but possibly the expectation of what the tapping should do is not what people are expecting.  For instance one of the tickets compares the experience of selecting text in SN to Apple mail, saying that Apple mail is much easier to use.  Comparing the two just now, and in Apple mail to highlight text it uses a long press, there is not a cursor scan mode.

@jleandroperez and @eshurakov I think we can close this issue if you think the behavior above is what you would expect, but I wonder if a discussion about if there is a experience design change that needs to happen to favor highlighting over scanning through the text.

**Comment by eshurakov** [comment] 2021-01-11 07:13
Thank you for detailed investigation @charliescheer!

I ran a quick test for the originally mentioned issue in Simplenote / Notes / Mail app. The behaviour is different depending on wether the keyboard is on screen or not:
* keyboard is on screen: long pressing puts the cursor into scan mode
* keyboard is not on screen: long pressing highlights the word 

And comparing mail app and Simplenote, when editing a note in Simplenote the keyboard is on screen most of the time. In mail app the keyboard is on screen only when you compose a new email.

From what I see the behaviour matches native apps, so I'm closing this issue.

**Closed by eshurakov** 2021-01-11 07:13 UTC
Labels: [feature] editor, bug
