### ISSUE TITLE
Running Unit Tests logs you out from the simulator

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-ios#1025] opened 2020-11-16 16:06 UTC
### What
Running Unit Tests from Xcode logs out currently logged in user from the iOS simulator.

### Why
Keeping the user logged in will make development experience better.

### How
Possible solution can be to check in the AppDelegate that we're running unit tests and don't create / run the app. 
Make sure that UI Automation / Screenshots are still working.

**Comment by charliescheer** [comment] 2021-03-15 07:30
I was working on some new tests today and noticed that my new tests were not logging the simulator out of the app.  I tested a few other test case classes and they also didn't log out the app.

So I did some digging and it is the KeychainMigratorTests class that is logging the simulator out.  The class only has two tests in it, both of them cause the logout issue.

I poked some more and the problem is the setter on KeychainMigrator.username.

`    var username: String? {
        set {
            UserDefaults.standard.set(newValue, forKey: Constants.usernameKey)
            UserDefaults.standard.synchronize()
        }
...
    }
`

Haven't come up with fix for this yet, but it seems that by changing the userDefaults username when we set it in the KeychainMigrator we are overriding the logged in simulator's user data.  Will look into this tomorrow

**Closed as completed** 2021-03-17 20:39 UTC
Labels: enhancement, Testing
