### ISSUE TITLE
Multiselect: note should be selected on releasing the finger, not right after the touch

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1307] opened 2021-06-03 21:37 UTC
### What
It feels like it would be more natural and consistent to have the note selected in edit mode on ‘fingerup’ (if that’s a thing), not on ‘fingerdown’. 

### Why
Two reasons:

1. This is done so in the such apps as Messages, Photos...
2. Currently, we have a weird case of instant selection followed by deselection when the finger touches the note and then moves:

https://user-images.githubusercontent.com/73365754/120716180-56975f00-c4ce-11eb-985f-461dc7f7e60e.mov

**Comment by SylvesterWilmott** [comment] 2021-06-17 12:25
Have to agree! I must say, I didn't even notice but now that it's called out, I can't unsee.

**Comment by charliescheer** [comment] 2021-06-28 05:24
I've been look into this, and from what I have been able to find there is not a way to choose selection on "press up" for tableview cell interaction (@eshurakov  @jleandroperez correct me if I am wrong)  Selection/Deselection is handled by a tap gesture which only happens on an instant.  If you tap it fires the method, continuing to press is a different gesture recognizer.  So what I think is happening in the tap and drag example is that the table view thinks you are tap selecting the cell, but when you start dragging, it changes it's mind/deselects because you didn't do a tap/begins scrolling through the tableview content instead.

What do you think instead about this idea.  What if we allowed for a tap and drag selection.  So any cell that is long pressed-and-dragged on will get temporarily selected, as the press continues and the cell changes the selected cell will change.  Finally when the tap is released the last cell that was pressed on will remain selected.  I think that would be possible.

**Comment by SylvesterWilmott** [comment] 2021-06-28 10:33
I would say this issue is low priority. I also don't think that we shouldn't make any deliberate changes to the default table cell selection interaction and I think this issue is more an observation that there is a difference between which event (finger up/finger down) is used to initiate the selection. In normal usage it's not much of an issue. The problem mentioned above regarding the blinking cells can actually be reproduced in mail.app as well by tapping and then scrolling.

**Comment by charliescheer** [comment] 2021-06-28 20:55
Sounds good.  I will drop this one off my list for now.  My sense is that we should close this one since it isn't a matter of choosing when the selection takes place, and would involve overwriting the system selection mechanism to make any changes.  What do you think @SylvesterWilmott ?

**Comment by charliescheer** [comment] 2024-04-17 16:58
fixed in https://github.com/Automattic/simplenote-ios/pull/1560

**Closed as completed by charliescheer** 2024-04-17 16:58 UTC
Labels: enhancement, [feature] note list
