### ISSUE TITLE
Unable to complete login with WordPress.com and 2FA on a fresh install

### ISSUE THREAD

**Issue by allendav** [Automattic/simplenote-ios#862] opened 2020-08-31 22:51 UTC
### Expected

If you "tab away" to get a 2FA code from, say, Google Authenticator, and then tab back, the web view becomes non-responsive and you are unable to complete login.

### Observed

Installed 4.23 fresh on iOS 13.6.1 on an iPhone XR
Attempted to sign in using WordPress.com. Was able to paste in username and password, but on returning to paste in 2FA code, found web view unresponsive.

p2XJRt-2hG-p2

### Reproduced

Yes, almost consistently. Out of 5 or so attempts, only made it past the 2FA prompt once and I'm not sure what I did differently then.

### Where did you see the bug

- System Make: iPhone
- System Model: XR
- OS: iOS
- OS version: 13.6.1 
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 4.23

**Comment by jleandroperez** [comment] 2020-09-09 16:28
Hi there @allendav,

Sorry to bug you again!! Mind taking a quick peek and check if it's still happening?

I'm afraid I can't repro on my end. Thanks in advance!!

**Comment by jleandroperez** [comment] 2020-09-15 20:43
Closing as cannot reproduce.

**Please feel free to reopen if needed**

Thank you!

**Closed by jleandroperez** 2020-09-15 20:43 UTC
