### ISSUE TITLE
Blockquote adds newline character for every ">" sign

### ISSUE THREAD

**Issue by brbrr** [Automattic/simplenote-ios#169] opened 2017-10-31 17:57 UTC
When adding a single-line blackquote(`> some quote`) it will render as 2 line quote:

```
> some quote
> /n
```

It looks even much buggy when nesting quotes like so:

```
> quote level 1
> > quote level 2 
```

To reproduce: 
1. Create a new note
2. add a single line quote: `> some quote`
3. Check note preview

![img_46abfc763d93-1](https://user-images.githubusercontent.com/5654161/32240200-5e2c07ba-be75-11e7-8833-7325c804e694.jpeg)

![img_ae1175bc9175-1](https://user-images.githubusercontent.com/5654161/32240255-8cc60dc8-be75-11e7-9b35-6290f89f95c8.jpeg)

Web app renders this note correctly: http://simp.ly/publish/yXF4Xz

**Comment by roundhill** [comment] 2018-07-09 22:09
Hmm, I can't reproduce this. Is this still occurring for you @brbrr?

**Comment by bummytime** [comment] 2019-05-14 03:44
Just tested the single line blockquote in Simplenote 4.7.0 — I am not seeing this issue. Closing for now.

**Closed by bummytime** 2019-05-14 03:44 UTC
