### ISSUE TITLE
Landscape mode typing results in note bouncing up and down

### ISSUE THREAD

**Issue by mokagio** [Automattic/simplenote-ios#896] opened 2020-09-28 06:44 UTC
### Expected
When I type in landscape mode, the text area stays still.

### Observed
When I type in landscape mode, the text area does a little scroll-up and scroll-down. It seems in sync with the key bubble.

#### Recording

![RPReplay_Final1600978968 2020-09-28 16_39_40](https://user-images.githubusercontent.com/1218433/94398618-3b3ebc00-01a9-11eb-9d3f-7663f9e2bc46.gif)

### Reproduced
Unfortunately, I'm **not able to reproduce this anymore**. Neither in the same note, nor in a new note.

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|iPhone 7|iOS 14.2 beta 1|v4.25 beta 4.25.0.0

**Comment by jleandroperez** [comment] 2020-10-12 19:29
Closed as duplicate of #13. 

Thank you Gio!!!

**Closed as completed by jleandroperez** 2020-10-12 19:29 UTC
Labels: duplicate
