### ISSUE TITLE
Remember last scroll position in each note

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#5] opened 2016-08-14 16:03 UTC
We used to have this. Adding this so we don't forget to consider it in the future.

In terms of support, this usually manifests as users asking for a button or shortcut to quickly get to the end of long notes. I think remembering scroll position is probably better.

requested #2563046-t

Originally opened by @mikejohnstn

**Comment by jleandroperez** [comment] 2019-10-23 04:59
Closing as duplicate of #66. Although this one is the oldest entry... I'm picking up the later since it's got a bit of extra feedback.

Thanks everyone!!

**Closed by jleandroperez** 2019-10-23 04:59 UTC
Labels: feature request
