### ISSUE TITLE
`Trash` is named `Trash-noun` in sidebar

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1440] opened 2021-09-21 13:58 UTC
### Expected
`Trash` should be named `Trash`

### Observed
In 4.45.0.0 it's called `Trash-noun`:
![photo_2021-09-21 16 54 36](https://user-images.githubusercontent.com/73365754/134183879-2fc0b18d-d619-4899-b0bc-43fbddbbc2ba.jpeg)

### Reproduced
1. Open sidebar ~> `Trash-noun` is shown instead to `Trash`

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.7.1|4.45.0.0

**Comment by charliescheer** [comment] 2021-10-01 15:03
This was caused by an issue with the script that loads translations and was fixed with https://github.com/Automattic/simplenote-ios/pull/1437

p1632243238011400?thread_ts=1632232767.008400&cid=C01KRRK0MLJ-slack-C01KRRK0MLJ

**Closed as completed by charliescheer** 2021-10-01 15:03 UTC
Labels: bug
