### ISSUE TITLE
[Translation] Non English - the word for "Trash" doesn't translate. 

### ISSUE THREAD

**Issue by rfaile313** [Automattic/simplenote-ios#564] opened 2019-12-26 16:48 UTC
Everywhere the French word "Trash" is supposed to appear, (poubelle) it appears as "Trash-Noun" or "Trash-Verb"

### Expected
"Trash" should translate from English to French

### Observed
"Trash" remains in English as either "Trash-Noun" or "Trash-Verb"

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
> 1. Change Language on Device to French
> 2. Open Simplenote App
> 3. Anywhere Trash should be translated, it remains in English - the Menu is a quick place to check.

User's Screenshot:

![example](https://user-images.githubusercontent.com/13829168/71483276-ac8db080-27cc-11ea-9a4b-5ac1f8967de3.png)

I was able to replicate this on my Apple iPhoneX iOS 13.3 Simplenote 14.4.2:

![img_0926](https://user-images.githubusercontent.com/13829168/71483341-ff676800-27cc-11ea-9213-1e1315e17430.png)

#user-report 2585745-zen

**Comment by charliescheer** [comment] 2020-01-13 04:45
Problem is happening on other languages besides French.  Updated title to reflect

**Comment by rachelmcr** [comment] 2020-03-25 15:02
I just noticed this issue while testing 4.17.0.0 TestFlight beta in various non-English languages. @jleandroperez How much time would it take to fix this one? It seems like a pretty significant broken window for non-English users.

**Comment by codebykat** [comment] 2020-04-30 23:55
Reported by a user for Russian in #2933866-zen. I'm seeing the translation in Glotpress so not sure what the issue is. https://translate.wordpress.com/projects/simplenote%2Fios/ru/default/?filters%5Bterm%5D=trash&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by codebykat** [comment] 2020-05-01 00:01
I don't know how this all works, but it looks like this file was updated by @charliescheer in #574  and that change was later overwritten by @loremattei in 33f0d452e4804762859972d9363a2012f328768a

**Comment by charliescheer** [comment] 2020-05-01 04:14
Yeah, I had come up with a fix for it, but after a chat with @jleandroperez removed the PR because the fix would have been over written when the strings were pulled from glotpress and the app was published.  

Interestingly, if you look at the localizable strings in the xcode project, none of the languages other than English has "Trash-verb" in them.  They all have "Delete" where trash-verb should be.  

So possibly there is an issue uploading the newest/correct translations from Glotpress?

**Comment by loremattei** [comment] 2020-05-01 07:48
This is interesting. I took a look and it seems to be an issue with how GlotPress exports the strings for iOS: 

https://github.com/GlotPress/GlotPress-WP/blob/d44a49cc5c4ab0e116b281a5b366a79c2c639c6f/gp-includes/formats/format-strings.php#L77

It looks like it uses the _original_ string as string id, instead of the provided key.

The result is that both the translations are in the file, but they have the same "Trash" id and not what XCode expects. 
For example, these are the entries in the it-IT file: https://github.com/Automattic/simplenote-ios/blob/38ea817c503f321e5de7a6deaca442b89e3233b5/Simplenote/it.lproj/Localizable.strings#L501 . From the comments, it's clear that these are noun and verb, but the string id is the same. 

I'm not sure how we can handle this... @akirk do you happen to have any suggestion?

**Comment by akirk** [comment] 2020-05-01 12:13
Since this is on translate.wordpress.com we can just change the code. I'll update it.

**Comment by akirk** [comment] 2020-05-01 12:20
https://github.com/GlotPress/GlotPress-WP/pull/1105

**Comment by akirk** [comment] 2020-05-01 12:25
The export (for example https://translate.wordpress.com/projects/simplenote%2Fios/it/default/export-translations/?format=strings) now produces a correct file. Could you take it from here?

**Comment by loremattei** [comment] 2020-05-01 13:47
Thank you @akirk! You rock! We'll use it to build the next release.

**Comment by jleandroperez** [comment] 2020-05-01 19:36
Apologies I never got in time to this issue. I did check on it, and indeed, tooling issue (non code related!!).

Thanks eeeeeveryone!!!

**Comment by jleandroperez** [comment] 2020-06-08 15:41
Fix verified in latest appstore release. Closing this one, thank you Alex + Lore!!

**Closed by jleandroperez** 2020-06-08 15:41 UTC
Labels: bug
