### ISSUE TITLE
Sync: iPhone note synced to iMac only when app is relaunched on iPhone

### ISSUE THREAD

**Issue by kriskorn** [Automattic/simplenote-ios#229] opened 2018-09-18 11:29 UTC
User has reported this intermittent behaviour on iPhone and iMac:

> I added a line or 2 of text into my iPhone. 
> Several minutes later I went to my iMac and wanted to add to the note there. But the note hadn’t updated. 
> I checked the iPhone app. All seemed well. So I killed the app with a swipe up and relaunched it. Instantly the note updated on the iMac.

I checked previous issues, but could not find anything related. 
Both of their devices are using the latest version of Simplenote.

Simplenote for iPhone: 4.64. 
Simplenote for Mac: 1.3.6 
iOS: now 12, but was the latest version before that.

1407238-zen

**Comment by damiannep** [comment] 2018-11-08 05:46
We have another report of this from the same user in #1545419-zen.

**Comment by crankygeologist** [comment] 2019-02-09 02:00
I also have this issue.

Simplenote 4.6.8 on iOS 12.1.4
Simplenote 1.4.1 on macOS 10.14.3

**Comment by charliescheer** [comment] 2021-01-11 03:42
Could not reproduce on iPhone 8 iOS 14.3 SN 4.29

Content added to notes on iOS appeared on my mac with in a few seconds and vise versa.  The original report mentioned that they saw this issue on their to do list, so tried creating a list and adding to the top of the note, as described, and the still the syncing worked fine.

Closing issue.

**Closed by charliescheer** 2021-01-11 03:42 UTC
Labels: bug
