### ISSUE TITLE
PUBLISH or PINNED TO TOP or MARKDOWN buttons hard to read with larger font

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#520] opened 2019-11-06 17:48 UTC
### Expected
If you use a larger font on an iOS device you should be able to see and read the titles for the different action buttons that appear in the note settings

### Observed
However if you are using a large font, the font becomes too big for the button to contain so you only see part of the button title:
<img src="https://cdn-std.droplr.net/files/acc_593859/VpQoIn" />

the different buttons are also handling the text formatting differently, some are squishing the type some are only displaying some of the type.

iPhone 8, iOS 13.2, Simplenote 4.12

**Comment by jleandroperez** [comment] 2019-11-15 14:43
Closing as duplicate of #457. We'll be redoing the action sheet soon.

Thank you Charlie!!

**Closed by jleandroperez** 2019-11-15 14:43 UTC
Labels: bug
