### ISSUE TITLE
Note Editor: Tag Auto Complete Not Adding Correct Tag

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/simplenote-ios#286] opened 2019-02-25 18:29 UTC
#### Steps to reproduce
1. Open a note in the editor.
2. Attempt to add a tag to the note that you already have in the app.
3. Type the first few characters of the tag.
4. Tap on the auto-completed tag above the tag entry section.

#### What I expected
The full tag to be added to the note.

#### What happened instead
Only the first few characters that you've typed are added as the tag.

#### Simplenote version
4.6.9

#### iOS version
12.1.4

#### Screenshot / Video

Video link: https://d.pr/free/v/tVlsRk

![Screenshot of additional tags](https://d.pr/free/i/Lw8F3Q+)

(Image link: https://d.pr/free/i/Lw8F3Q )

First reported by user in 1821753-zen

**Comment by pauljacobson** [comment] 2019-02-26 13:12
Hi there, we received another report of this issue in 1823980-zen. Here's the user's report:

>How can we help?: Choosing tags after typing the first couple of letters is no longer working. The close matches come up, but when you choose one, all that it added as a tag is the first letters originally typed.
>
>This makes tagging on iOS VERY cumbersome!

**Comment by ashercantrell** [comment] 2019-03-05 16:00
Paul's user came back and provided more details about their setup:

> IOS 12.1.4 
Simplenote 4.6.9

**Comment by charliescheer** [comment] 2019-05-23 23:36
I did a little testing on this on 4.7.  At first what I was seeing was different than what is in the video.  I was seeing the correct notes being assigned to the correct tags, but new tags were being created under for the shortened tag, so if I typed in tes for testing and tapped on it, the note would be assigned to testing, but a tag tes would be created with nothing assigned to it.'

While trying to capture a screenshot of this behavior, for some reason it stopped happening and now I can't make it do it again.  Very strange.

**Comment by koke** [comment] 2020-10-23 14:24
Another case in 3425530-zen. I was able to reproduce the issue on 4.26.

**Comment by rossanafmenezes** [comment] 2020-10-27 16:23
Another report here 3441853-zen

iPadOS 14.1 
SN 4.26 

I tried that on my own iPad 7th gen iOS 14.0.1 SN 4.26 (one update pending) and I was not able to reproduce the issue.

**Comment by reginabally** [comment] 2020-10-28 07:45
Another report in 3439709-zen.

iPhone 8
iOS 14.1
Simplenote iOS v4.26

**Comment by codebykat** [comment] 2020-10-28 16:16
Happening to me too on latest beta 4.26.0.1.

**Comment by eshurakov** [comment] 2020-11-03 07:54
Another report in 3459614-zen

**Comment by rossanafmenezes** [comment] 2020-11-04 17:40
Another report here:

3451401-zen

Version 4.26
ios 12.4.8
iPhone 6

**Comment by mliq** [comment] 2020-11-18 20:02
I have the latest version with the bugfix in release notes (4.27) but am still seeing this issue. 

Version 4.27
iOS 14.2
iPhone 12 Pro 

Tried:
- Force quit app and reopen.
- Reboot phone.

Could you please reopen issue @jleandroperez? Thank you for the amazing app! I wish I could pay for it.

**Comment by jleandroperez** [comment] 2020-11-18 20:20
Hi there @mliq,

I'm sorry you're still having issues!! Would it be possible to get a sample video demoing the glitch?

**Comment by jleandroperez** [comment] 2020-11-18 20:23
P.s.: Autocomplete is expected to work as soon as you actually tap over any of the Tag suggestions. (Cannot repro anymore in 4.27 // latest AppStore).

Thank you!

**Comment by mliq** [comment] 2020-11-26 15:58
@jleandroperez working for me now, thank you!

I wonder why it changed? 🤔
The only difference is I upgraded to iOS 14.2.1, could that have done it?

**Comment by jleandroperez** [comment] 2020-12-02 21:53
Huge mystery! Not really sure, we don't have code meant specifically for 14.2.1.

Closing again (I cannot repro on my end!). If needed please feel free to reopen.

Thanks for the report @mliq !!

**Closed by jleandroperez** 2020-12-02 21:53 UTC
Labels: [feature] tags, bug
