### ISSUE TITLE
Clicking on a note after searching for a tag makes the app crash

### ISSUE THREAD

**Issue by alexchhll** [Automattic/simplenote-ios#1195] opened 2021-03-08 16:42 UTC
Clicking on a note after searching for a tag makes the app crash

### Expected
App doesn't crash

### Observed
Clicking on a note after searching for a tag makes the app crash

### Reproduced

1. Create a note.
2. Add a tag.
3. Go to your list of notes.
4. Search for the previously added tag.
5. On the list of notes that contain that tag, click on the note.

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone XS Max|iOS 14.4|Simplenote 4.32

**Comment by pachlava** [comment] 2021-03-08 19:40
@alexchhll thank you! Reproduced this too.

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|iOS 14.4|Simplenote 4.33.0.0

**Comment by eshurakov** [comment] 2021-03-09 08:42
Thank you for reporting this @alexchhll! Closing this one in favour of #1193 as the root cause is the same.

**Closed as completed by eshurakov** 2021-03-09 08:42 UTC
Labels: bug, crash
