### ISSUE TITLE
WordPress SSO Viewport Issue

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#915] opened 2020-10-13 17:06 UTC
Thank you @guarani for reporting this one!!

[login.mov.zip](https://github.com/Automattic/simplenote-ios/files/5372959/login.mov.zip)

**Comment by charliescheer** [comment] 2021-01-13 21:04
Was not able to reproduce, closing

**Closed as completed by charliescheer** 2021-01-13 21:04 UTC
Labels: bug
