### ISSUE TITLE
Preview mode default

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#137] opened 2017-03-07 08:15 UTC
Allow preview mode to be the default view when you open a note.

Same as this request - https://github.com/Automattic/simplenote-electron/issues/381 - but for iOS

Requested in #3092681-t

**Comment by jleandroperez** [comment] 2019-08-20 13:13
Closing as duplicate of #403. (Actually it's the other way around, but #403 links to the Android issue that has been already solved!!).

Hope you're doing great Rachel, thank you!

**Closed by jleandroperez** 2019-08-20 13:13 UTC
Labels: [feature] settings, enhancement
