### ISSUE TITLE
Text disappears from notes on iOS, but still appears on other devices

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/simplenote-ios#100] opened 2016-11-02 01:35 UTC
A user reports in 2899711-t that since iOS 10.1 their text often disappears from the iOS app moments after they type it, but if they look at the note on another device (Linux in this specific case) the text is there. If they add additional content from the other device and sync, iOS then shows all of the content.

Here's the specific versions in the example I worked on: 
"The iPhone is on iOS 10.1 with Simplenote v4.4.1. I have 2 Linux
workstations, with Linux Mint 17.3 and Linux Mint 18, both are running
Simplenote v1.0.5."

**Comment by rachelsquirrel** [comment] 2016-11-02 12:46
I've got a similar report here #2901982-t.

It sounds like the Linux or Windows version of the app is overwriting the changes.

**Comment by chad1008** [comment] 2016-11-03 14:18
The above user in #2901982-t replied with some additional details:

--
1. On the PC, I created a new note and added some text.
2. Leaving this note in the active window, I opened Simplenote on iPhone and made sure that the note got synchronized.
3. I tried to edit the note on iPhone and noticed a strange thing: i) every few seconds all changes on iPhone disappeared, leaving the note as it was at the moment of opening, but ii) at the same time, all these changes were reflected in the PC app. I have been starting to type a sentence five times on iPhone, and all the typed text disappeared five times. But at the same time, on PC all five attempts got synchronized, so five identical unfinished sentences were added one after another.
4. I closed the PC app and typed some words again on iPhone. They didn’t disappear.
5. I opened the PC app back and noticed that this time the note was synchronized exactly with the latest iPhone version.

**Comment by rdpzycho** [comment] 2016-11-19 19:27
A bit of update, I'm the user in 2899711-t.

After updating to v1.0.6 on both Linux machines, with the iOS app open, text also disappears now while editing on the Linux machine with the edits inconsistently syncing (some of the text ends up at the end of the note or on the line where the last edit on the iOS app happened).

With only the iOS app open, or Simplenote running on the Linux machines (simultaneously) only, editing and syncing is normal.

**Comment by Samizdat2003** [comment] 2017-01-19 21:12
I'm experiencing the same problem reported above, namely: "text often disappears from the iOS app moments after they type it, but if they look at the note on another device... the text is there. If they add additional content from the other device and sync, iOS then shows all of the content"

Specifically, I'm using the latest Windows client (v1.07) on two Windows computers (one running Windows 7 and the other running windows 10) and also the latest iOS client (v4.4.2) on an iPhone 6+ running iOS 10.2.

I've been experiencing this problem for a while with earlier releases of the iOS client. I had hoped that the 4.4.2 iOS client release had solved this problem, but it just recurred.

It seems to occur only when the Windows client is open and running. With the 4.4.2 release, I have encountered the problem when the Windows client is running on my Windows 7 machine, but not (so far) when it's running on my Windows 10 machine. However I don't know if that is consistent or significant as I haven't tested it all that thoroughly.

Hope this information helps!

**Comment by Samizdat2003** [comment] 2017-02-22 16:17
Updating my post above: Since upgrading to the new Windows client (v 1.08) I have not been able to reproduce this issue, so perhaps it is now resolved.

**Comment by bummytime** [comment] 2019-05-14 03:18
Closing.

**Closed by bummytime** 2019-05-14 03:18 UTC
Labels: bug
