### ISSUE TITLE
Tables Not Formatting

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-ios#219] opened 2018-08-27 20:04 UTC
I used the following Markdown to create a table in Simplenote:

```
Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
```

In the macOS app it renders correctly:
![screen shot on 2018-08-27 at 14_45_05](https://user-images.githubusercontent.com/19782997/44682743-ddf44180-aa09-11e8-8ecd-a95012316a55.png)

But in iOS it does not:
![img_6314](https://user-images.githubusercontent.com/19782997/44682767-eb113080-aa09-11e8-86b5-a2c0eb37ea10.jpeg)

iOS version: 4.6.4
macOS version: 1.3.7

**Comment by roundhill** [comment] 2018-08-28 17:59
Dupe of #189

**Closed by roundhill** 2018-08-28 17:59 UTC
Labels: bug, duplicate
