### ISSUE TITLE
Markdown: Irregular Spacing

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#949] opened 2020-10-26 15:10 UTC
```
It seems to me that this is not working consistently as the inline space is not regular, or there is no control over it.
```

h/t @marianearchimbaud (Thank you for reporting this Mariane!!

<img width="300" alt="Screen Shot 2020-10-26 at 12 08 37" src="https://user-images.githubusercontent.com/1195260/97190111-19bef900-1784-11eb-9e90-f414283758ec.png">

<img width="300" alt="Screen Shot 2020-10-26 at 12 08 29" src="https://user-images.githubusercontent.com/1195260/97190077-1297eb00-1784-11eb-9da6-9f2984192697.png">

**Comment by charliescheer** [comment] 2021-01-13 21:49
This is a duplicate of https://github.com/Automattic/simplenote-ios/issues/707

closing

**Closed as completed by charliescheer** 2021-01-13 21:49 UTC
Labels: bug, [feature] markdown
