### ISSUE TITLE
Words are in black for first time viewing

### ISSUE THREAD

**Issue by Bread7** [Automattic/simplenote-ios#468] opened 2019-10-14 06:24 UTC
iPhone Model: iPhone XS
IOS Version: IOS 13
Simplenote Theme: Dark

For each new session of Simplenote, the first note you see will cause all current text to be black but new written text are in white.

Video: 
![bug](https://user-images.githubusercontent.com/39032432/66730414-2e379880-ee84-11e9-8a77-44e8a9c2ea85.gif)

**Comment by jleandroperez** [comment] 2019-10-14 12:34
Closing this one as duplicate of #40. Fixed via #441 

Thank you @Bread7 !!

**Closed by jleandroperez** 2019-10-14 12:34 UTC
Labels: bug
