### ISSUE TITLE
Alphabetise tag list

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#21] opened 2016-08-14 16:20 UTC
It would be great to be able to sort the list of tags alphabetically

another request #2685197-t

Another request #2726533-t

Opened by @rachelsquirrel

**Comment by rantoncuadrado** [comment] 2017-10-20 12:38
#43423423-zen

**Comment by gracie** [comment] 2018-06-10 15:37
Also requested in #1211447-zen

**Comment by cademis** [comment] 2018-09-22 11:48
+1 for this change. I understand this is by design cross-platform, however, I find myself manually ordering my tags alphabetically to allow me to find tags quickly (150+ tags)

**Comment by Shtalin** [comment] 2019-08-17 20:12
Why it is open? I can sort tags

**Comment by jleandroperez** [comment] 2019-08-20 14:01
Closing this one since there's an option to Sort Tags alphabetically.

**Closed by jleandroperez** 2019-08-20 14:01 UTC
Labels: enhancement, feature request
