### ISSUE TITLE
IPhone selection handling not working 

### ISSUE THREAD

**Issue by jgwill** [Automattic/simplenote-ios#476] opened 2019-10-21 07:55 UTC
### Expected
iOS selection to work fine as it was usually works and like other apps does.
Be able to handle and extend selection by dragging the handle 

### Observed
Content do not stay selected the usual drag of the selection handle brings on the preview page

### Reproduced:
> 1. Write content in latest iOS SIMPLENOTE
> 2. Double tap to select a word 
> 3. Try dragging the handle to extend selection 

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)*** 
IPhone 8 latest IOS (on date of posting the issue )

Make|Model|iOS Version|App Version
-|-|-|-
DEVICE_MAKE|DEVICE_MODEL|IOS_VERSION|APP_VERSION

**Comment by brightghost** [comment] 2019-10-21 16:46
I am seeing the same in my iPhone SE with iOS 10.1.3. Selecting text is fully broken except double-tapping to select a single word.

**Comment by msilbers** [comment] 2019-10-22 17:35
Reported in #435 already

**Comment by jleandroperez** [comment] 2019-10-23 04:01
Closing as duplicate of #472. Scheduled to be fixed in 4.13!

Thanks everyone for bringing this up!!

**Closed by jleandroperez** 2019-10-23 04:01 UTC
Labels: bug
