### ISSUE TITLE
Paste doesn't work in iOS 11

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-ios#150] opened 2017-06-30 09:39 UTC
I've got a report that pasting from a web browser into a new note causes Simplenote to crash in iOS 11. 

#3292468-t

**Comment by rachelsquirrel** [comment] 2017-07-03 13:15
User reports this is working now so I'm closing this.

**Comment by jleandroperez** [comment] 2017-07-03 13:51
Thanks @rachelsquirrel !!

**Comment by lizkarkoski** [comment] 2017-07-07 02:02
There's a user on Twitter reporting this same issue. 

https://twitter.com/pazimzadeh/status/883117254174527493

Pasting in iOS 11 on iPad with the Beta app causes the app to crash. 

Yesterday I was helping another user on Twitter with the same issue using the Beta app on iOS 11 on their iPhone 6 plus. I don't have a link to that conversation as they haven't replied again.

**Comment by rachelsquirrel** [comment] 2018-01-23 10:21
The "Select | Select All | Paste" options often disappear before you can select one of them. 

#910736-zen

**Comment by Robertght** [comment] 2018-03-01 06:27
Another one: #981236-zen

**Comment by Robertght** [comment] 2018-06-21 07:11
+1 #1210042-zen

**Comment by charliescheer** [comment] 2020-03-03 09:32
I spent some time just now trying to replicate this can could not replicate: 
iOS 13.3.1 
Simplenote 4.15.1
iPhone 8

I could not replicate the problem of the Select | Select All | Paste disappearing 

or replicate a a crash problem when trying to paste into Simplenote from a browser or otherwise.

Has anyone been able to replicate this recently?

**Comment by jleandroperez** [comment] 2020-09-08 20:04
Closing this issue as cannot reproduce.

iOS 14 / Simplenote 4.24.

Apologies about the late reply @charliescheer !!  Thank you for checking!!

**Closed by jleandroperez** 2020-09-08 20:04 UTC
Labels: [feature] editor, bug, not verified
