### ISSUE TITLE
Live Update for Markdown Preview

### ISSUE THREAD

**Issue by ColaIan** [Automattic/simplenote-ios#1257] opened 2021-04-24 13:50 UTC
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
***(Required)*** What is the feature you are requesting?  Add a concise description of the feature being requested.
A Live Update feature for the Markdown Preview when the note is being edited on other devices

### Why
***(Required)*** Why are you requesting this feature?  Add a concise description of the problem this feature solves.
It would be convienient for example when I'm editing the note on PC, and to showcase a markdown version of it to other people on iPad while having the possibility to update the note in realtime.

### How
***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate how the feature could be done.
N/A

**Comment by jleandroperez** [comment] 2021-04-25 22:21
Closing as duplicate of #305.

Adding a +1 vote in our (internal) feature request system.

Thanks for reaching out!

**Closed as completed** 2021-04-25 22:21 UTC
Labels: feature request
