### ISSUE TITLE
Fingerprints not required to access the app again

### ISSUE THREAD

**Issue by RafaelFunchal** [Automattic/simplenote-ios#120] opened 2017-01-02 17:13 UTC
A user reported the following behavior:

> Love the app on my iphone. I've just noticed that things are not as secure as they once were. I use fingerprints, ios10.2, on an iPhone 6. When I switch away from Simplenote to another app I am not required to re-enter my passcode or fingerprint. In the past every time I came back to the app I had to log in. 

As I don't have an iPhone to test, @roundhill tested it and could also reproduce it. His thoughts about it:

> It seems to happen when you are in the note editor, but not in the list when you leave the app

**Comment by linickx** [comment] 2017-01-17 09:29
👍 I've used the [contact ](https://simplenote.com/contact-us/) page to report a similar issue.

**Comment by roundhill** [comment] 2017-01-18 18:56
This is a dupe of #87

**Comment by jleandroperez** [comment] 2017-01-19 10:05
Closing as dupe of #87

**Closed by jleandroperez** 2017-01-19 10:05 UTC
Labels: duplicate
