### ISSUE TITLE
Diacritic marks in iPad Preview mode sized differently

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-ios#784] opened 2020-06-23 13:27 UTC
### Expected

That letters with diacritic marks would keep the same size as other letters when previewed in iPad. 

### Observed

When you preview a post written in markdown with diacritic letters, some letters like `ż`, `ę`, `ś`, `ć`, and `ą`.

### Reproduced

> 1. Go to Simplenote on iPad and write a post with mardown enabled
> 2. Add some of the diacritic letters such as provided above (you can install a Polish keyboard for example and just long press on some of the main keys to use the characters provided)
> 3. Switch to the Preview mode and you'll see the difference in font size for those characters.

![IMG_B6401F0D3391-1](https://user-images.githubusercontent.com/10325627/85409095-45736d80-b55d-11ea-8b78-44b0c4c63bab.jpeg)

Make|Model|iOS Version|App Version
-|-|-|-
iPad|Air 2|13.4.1|14.9

(user also reported this in iPad with iOS 13.5.1 with same app version. This is not reproduced on the iPhone app)

Reports in 3035351-zen

**Comment by charliescheer** [comment] 2021-01-13 02:18
duplicate of #446 
was not able to repo, closing

**Closed by charliescheer** 2021-01-13 02:18 UTC
Labels: [feature] preview, bug
